/*
Name: Logan Bohan-Moulton
Course: CNT 4714 - Spring 2019
Assignment title: Project 3: Two-Tier Client-Server Application Development With MySQL and JDBC
Date: Thursday March 21, 2019
Class: GUI.java (main)
*/
package project3;

import com.mysql.cj.jdbc.MysqlDataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;


public class GUI extends javax.swing.JFrame {

    private ResultSetTableModel tableModel;
    private Connection connection;
    private MysqlDataSource dataSource = new MysqlDataSource();
 
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sqlTextArea = new javax.swing.JTextArea();
        sqlTitle = new javax.swing.JLabel();
        driverLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        driverDropDownBox = new javax.swing.JComboBox();
        urlDropDownBox = new javax.swing.JComboBox();
        userTextField = new javax.swing.JTextField();
        passTextField = new javax.swing.JPasswordField();
        databaseTitle = new javax.swing.JLabel();
        executeButton = new javax.swing.JButton();
        clearSQLButton = new javax.swing.JButton();
        connectButton = new javax.swing.JButton();
        connectionTextField = new javax.swing.JTextField();
        clearResultButton = new javax.swing.JButton();
        tableTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SQL Client GUI");

        sqlTextArea.setColumns(20);
        sqlTextArea.setRows(5);
        jScrollPane1.setViewportView(sqlTextArea);

        sqlTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sqlTitle.setForeground(new java.awt.Color(0, 51, 255));
        sqlTitle.setText("Enter An SQL Command");

        driverLabel.setBackground(new java.awt.Color(204, 204, 204));
        driverLabel.setText("JDBC Driver");

        urlLabel.setBackground(new java.awt.Color(204, 204, 204));
        urlLabel.setText("Database URL");

        userLabel.setBackground(new java.awt.Color(204, 204, 204));
        userLabel.setText("Username");

        passLabel.setBackground(new java.awt.Color(204, 204, 204));
        passLabel.setText("Password");

        driverDropDownBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "com.mysql.cj.jdbc.Driver" }));

        urlDropDownBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jdbc:mysql://localhost:3312/project3" }));

        passTextField.setToolTipText("");

        databaseTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        databaseTitle.setForeground(new java.awt.Color(0, 0, 255));
        databaseTitle.setText("Enter Database Information");

        executeButton.setBackground(new java.awt.Color(204, 255, 204));
        executeButton.setForeground(new java.awt.Color(0, 204, 0));
        executeButton.setText("Execute SQL Command");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });

        clearSQLButton.setBackground(new java.awt.Color(255, 204, 204));
        clearSQLButton.setForeground(new java.awt.Color(204, 0, 51));
        clearSQLButton.setText("Clear SQL Command");
        clearSQLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSQLButtonActionPerformed(evt);
            }
        });

        connectButton.setBackground(new java.awt.Color(51, 0, 255));
        connectButton.setForeground(new java.awt.Color(255, 255, 204));
        connectButton.setText("Connect to Database");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        connectionTextField.setEditable(false);
        connectionTextField.setBackground(new java.awt.Color(0, 0, 0));
        connectionTextField.setForeground(new java.awt.Color(255, 0, 0));
        connectionTextField.setText("No Connection Now");

        clearResultButton.setBackground(new java.awt.Color(255, 255, 153));
        clearResultButton.setForeground(new java.awt.Color(255, 153, 0));
        clearResultButton.setText("Clear Result Window");
        clearResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearResultButtonActionPerformed(evt);
            }
        });

        tableTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableTitle.setForeground(new java.awt.Color(0, 51, 255));
        tableTitle.setText("SQL Execution Result Window");

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(resultTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(driverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(urlLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(passLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(userTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(urlDropDownBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                                    .addComponent(driverDropDownBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passTextField)))
                            .addComponent(databaseTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sqlTitle)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connectionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(connectButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearSQLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(executeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearResultButton)
                            .addComponent(tableTitle))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqlTitle)
                    .addComponent(databaseTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driverLabel)
                            .addComponent(driverDropDownBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urlLabel)
                            .addComponent(urlDropDownBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userLabel)
                            .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passLabel)
                            .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeButton)
                    .addComponent(clearSQLButton)
                    .addComponent(connectButton)
                    .addComponent(connectionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearResultButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        
        
        dataSource.setUser(userTextField.getText());
        dataSource.setPassword(passTextField.getText());
        dataSource.setURL(urlDropDownBox.getSelectedItem().toString());
        // Set credentials and URL from GUI for database connection
        
        try {
            connection = dataSource.getConnection();
            connectionTextField.setText(String.format("Connected to %s", urlDropDownBox.getSelectedItem().toString()));
        }
        catch(SQLException sqlException)
        {
            sqlException.printStackTrace();
            System.exit(1);
        }
        
    }//GEN-LAST:event_connectButtonActionPerformed

    private void clearSQLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSQLButtonActionPerformed
        sqlTextArea.setText(null);
    }//GEN-LAST:event_clearSQLButtonActionPerformed

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        String query = sqlTextArea.getText();
        
        try {
            tableModel = new ResultSetTableModel(dataSource, connection, query);
           if (query.substring(0, query.indexOf(' ')).equals("select"))
           {
            tableModel.setQuery(query);
           } else {
            tableModel.setUpdate(query);
           }
            resultTable.setModel(tableModel);
            jScrollPane2.setVisible(true);

        }
        catch (SQLException sql) {
            sql.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_executeButtonActionPerformed

    private void clearResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearResultButtonActionPerformed
        jScrollPane2.setVisible(false);
    }//GEN-LAST:event_clearResultButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearResultButton;
    private javax.swing.JButton clearSQLButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JTextField connectionTextField;
    private javax.swing.JLabel databaseTitle;
    private javax.swing.JComboBox driverDropDownBox;
    private javax.swing.JLabel driverLabel;
    private javax.swing.JButton executeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passTextField;
    private javax.swing.JTable resultTable;
    private javax.swing.JTextArea sqlTextArea;
    private javax.swing.JLabel sqlTitle;
    private javax.swing.JLabel tableTitle;
    private javax.swing.JComboBox urlDropDownBox;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
